# Generated by Django 3.0.2 on 2020-04-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.TextField(max_length=30)),
                ('password', models.TextField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('education', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('rono', models.BigIntegerField()),
                ('mono', models.BigIntegerField()),
                ('message', models.TextField(max_length=500)),
                ('level', models.TextField()),
            ],
        ),
    ]
