# Generated by Django 3.0.2 on 2020-04-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='status',
            field=models.TextField(default='unseen', max_length=20),
        ),
    ]
