# Generated by Django 3.0.2 on 2020-04-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_grievance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.TextField(max_length=30)),
                ('password', models.TextField(max_length=30)),
                ('education', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.TextField(max_length=30)),
                ('password', models.TextField(max_length=30)),
                ('education', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='CheckMember',
            new_name='College',
        ),
    ]
